services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=event-dim
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data