/*------------------------------------------
 * Generated by htmx-router                *
 * Warn: Any changes will be overwritten   *
-------------------------------------------*/

/* eslint-disable @typescript-eslint/no-explicit-any */
const client = {
	ThemeSwitcher: async (element: HTMLElement, props: any) => {
		const C = (await import("~/component/client/theme-switcher")).ThemeSwitcher;
		const r = await import("react-dom/client");
		r.createRoot(element).render(<C {...props} />);
	},
	Authenticate: async (element: HTMLElement, props: any) => {
		const C = (await import("~/component/client/authenticate")).Authenticate;
		const r = await import("react-dom/client");
		r.createRoot(element).render(<C {...props} />);
	},
}
export default client;
(window as any).CLIENT = client;