#!/usr/bin/env node
"use strict";

import { writeFile } from "fs/promises";
import { relative } from "path";

// import { GenerateClient } from "~/internal/compile/manifest";
import { CompileRouter } from "../compile/router.js";
import { ReadConfig } from "../cli/config.js";

const config = await ReadConfig();

console.info("Building router");
const routes = relative(config.router.output, config.router.folder).replaceAll("\\", "/").slice(1);
let source = `/*------------------------------------------
 * Generated by htmx-router                *
 * Warn: Any changes will be overwritten   *
-------------------------------------------*/
/* eslint-disable @typescript-eslint/no-explicit-any */\n`
	+ CompileRouter(routes);

await writeFile(config.router.output, source);


if (config.client) {
	// console.info("Building client island manifest");
	// await GenerateClient(config.client, true);
}