/*------------------------------------------
 * Generated by htmx-router                *
 * Warn: Any changes will be overwritten   *
-------------------------------------------*/
import { Counter } from "~/component/counter";
import ReactDOM from "react-dom/client";

const client = {
	Counter: (element: HTMLElement, props: any) => ReactDOM.createRoot(element).render(<Counter {...props} />),
};
export default client;
(window as any).CLIENT = client;